document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<!--|");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("  |");
document.writeln("   \/\/ /");
document.writeln("    |    看下面，球球你了-->");
document.writeln("");
document.writeln("<!--写在开头，如果你是这个网站的下一任管理人，希望你好好学习代码（当然可能后期我们搭建好了后台就不用学习代码了！！！=。=），在这个index的head上面，我要感谢很多人，在我制作网站的道路上，包括互联网上面的广大分享代码的朋友，美国的郑老师，国内的李老师，还有一个伟大而又传奇的男子，他神秘而又平易近人，他的脑子中充满了神奇的想法和取之不尽的灵感，这个人就是你们的师兄，我自己，无畏者，全智全能的神，妇女芳心纵火犯，可爱而又迷人的，令人爱不释手的，王智：）嘻嘻嘻嘻嘻-->");
document.writeln("<!--如果细数网站的发展，依托平台从wordpresss转变到了bootstrap，然后准备搭建一个后台（现在还没有搭建，今天我刚把图标更新上去，有点开心hh），以后还要去制作移动端和pc端的界面，不想做响应式了，响应式感觉兼容性有时候不是很好，不过偷懒的话感觉响应式基本是可以满足需求的（话说回来，反正我觉得怎么也轮不到我去做这件事了，我就玩玩响应式吧，交给后面的人去制作两套样式了hh）-->");
document.writeln("<!--反正闲来无聊不如考虑把这个网站正好当作一个写日记的平台，记录写可以分享的东西还算是不错的hhhhhh。");
document.writeln("  <head>");
document.writeln("  <meta charset=\'utf-8\'>");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\'>");
document.writeln("  <meta http-equiv=\'x-ua-compatible\' content=\'ie=edge\'>");
document.writeln("  <title>China PSC</title>");
document.writeln("  <!-ico图标啦~~~-->");
document.writeln("");
document.writeln("  <link rel=\'icon\' href=\'img/ico图标.ico\' type=\'image/x-icon\'>");
document.writeln("  <link rel=\'shortcut icon\' href=\'img/ico图标.ico\' type=\'image/x-icon\'>");
document.writeln("");
document.writeln("  <!-- Font Awesome -->");
document.writeln("  <link rel=\'stylesheet\' href=\'css/all.css\'>");
document.writeln("  <!-- Bootstrap core CSS -->");
document.writeln("  <link href=\'css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("  <!-- Material Design Bootstrap -->");
document.writeln("  <link href=\'css/mdb.min.css\' rel=\'stylesheet\'>");
document.writeln("  <!-- Your custom styles (optional) -->");
document.writeln("  <link href=\'css/style.min.css\' rel=\'stylesheet\'>");
document.writeln("  <style type=\'text/css\'>");
document.writeln("    /* Necessary for full page carousel*/");
document.writeln("    html,");
document.writeln("    body,");
document.writeln("");
document.writeln("    header,");
document.writeln("    .view {");
document.writeln("      height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Carousel*/");
document.writeln("    .carousel,");
document.writeln("    .carousel-item,");
document.writeln("    .carousel-item.active {");
document.writeln("      height: 100%;");
document.writeln("    }");
document.writeln("    .carousel-inner {");
document.writeln("      height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    @media (min-width: 800px) and (max-width: 850px) {");
document.writeln("      .navbar:not(.top-nav-collapse) {");
document.writeln("          background: #1C2331!important;");
document.writeln("      }");
document.writeln("  }");
document.writeln("");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("                          ");
document.writeln("<footer class=\'page-footer text-center font-small mt-4 wow fadeIn\'>");
document.writeln("");
document.writeln("    <!--Call to action-->");
document.writeln("    <div class=\'pt-4\'>");
document.writeln("      <!--<a class=\'btn btn-outline-white\' href=\'downloadfile.html\' target=\'_blank\' role=\'button\'>下载");
document.writeln("        <i class=\'fas fa-download ml-2\'></i>");
document.writeln("      </a>-->");
document.writeln("      <a class=\'navbar-brand btn btn-outline-white\' href=\'img/公众号二维码.jpg\' target=\'_blank\' role=\'button\'>微信公众号");
document.writeln("        <img src=\'img/微信公众号改.png\' style=\'width:15px\'> <!--<i class=\'fas fa-graduation-cap ml-2\'></i>-->");
document.writeln("      </a>");
document.writeln("      <a class=\'navbar-brand btn btn-outline-white\' href=\'https://mailchi.mp/323be7b7943d/v5ltn5gxg7\' target=\'_blank\' role=\'button\'>&nbsp;&nbsp;邮件订阅&nbsp;");
document.writeln("        <img src=\'img/邮件订阅改.png\' style=\'width:13px\'>  <!--<i class=\'fas fa-book ml-2\'></i>-->");
document.writeln("      </a>");
document.writeln("    </div>");
document.writeln("    <!--/.Call to action-->");
document.writeln("");
document.writeln("    <hr class=\'my-4\'>");
document.writeln("");
document.writeln("    <!-- Social icons -->");
document.writeln("    <!-- <div class=\'pb-4\'>");
document.writeln("      <a href=\'https://www.facebook.com/mdbootstrap\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-facebook-f mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'https://twitter.com/MDBootstrap\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-twitter mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'https://www.youtube.com/watch?v=7MUISDJ5ZZ4\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-youtube mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'https://plus.google.com/u/0/b/107863090883699620484\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-google-plus-g mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'https://dribbble.com/mdbootstrap\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-dribbble mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'https://pinterest.com/mdbootstrap\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-pinterest mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'https://github.com/mdbootstrap/bootstrap-material-design\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-github mr-3\'></i>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <a href=\'http://codepen.io/mdbootstrap/\' target=\'_blank\'>");
document.writeln("        <i class=\'fab fa-codepen mr-3\'></i>");
document.writeln("      </a>");
document.writeln("    </div> -->");
document.writeln("    <!-- Social icons -->");
document.writeln("");
document.writeln("    <!--Copyright-->");
document.writeln("    <div class=\'footer-copyright py-3\'>");
document.writeln("      © 2022 Copyright:<br/><a href=\'#\' target=\'_blank\'> 张彬 过程安全实验室 版权所有 https://china-psc.com </a>");
document.writeln("    </div>");
document.writeln("    <!--/.Copyright-->");
document.writeln("");
document.writeln("  </footer>");
document.writeln("  <!--/.Footer-->");
document.writeln("");
document.writeln("  <!-- SCRIPTS -->");
document.writeln("  <!-- JQuery -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/jquery-3.4.1.min.js\'></script>");
document.writeln("  <!-- Bootstrap tooltips -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/popper.min.js\'></script>");
document.writeln("  <!-- Bootstrap core JavaScript -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/bootstrap.min.js\'></script>");
document.writeln("  <!-- MDB core JavaScript -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/mdb.min.js\'></script>");
document.writeln("  <!-- Initializations -->");
document.writeln("  <script type=\'text/javascript\'>");
document.writeln("    // Animations initialization");
document.writeln("    new WOW().init();");
document.writeln("  </script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");