document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<!--|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("	|");
document.writeln("   \/\/ /");
document.writeln("    |    看下面，球球你了-->");
document.writeln("");
document.writeln("<!--写在开头，如果你是这个网站的下一任管理人，希望你好好学习代码（当然可能后期我们搭建好了后台就不用学习代码了！！！=。=），在这个index的head上面，我要感谢很多人，在我制作网站的道路上，包括互联网上面的广大分享代码的朋友，美国的郑老师，国内的李老师，还有一个伟大而又传奇的男子，他神秘而又平易近人，他的脑子中充满了神奇的想法和取之不尽的灵感，这个人就是你们的师兄，我自己，无畏者，全智全能的神，妇女芳心纵火犯，可爱而又迷人的，令人爱不释手的，王智：）嘻嘻嘻嘻嘻-->");
document.writeln("<!--如果细数网站的发展，依托平台从wordpresss转变到了bootstrap，然后准备搭建一个后台（现在还没有搭建，今天我刚把图标更新上去，有点开心hh），以后还要去制作移动端和pc端的界面，不想做响应式了，响应式感觉兼容性有时候不是很好，不过偷懒的话感觉响应式基本是可以满足需求的（话说回来，反正我觉得怎么也轮不到我去做这件事了，我就玩玩响应式吧，交给后面的人去制作两套样式了hh）-->");
document.writeln("<!--反正闲来无聊不如考虑把这个网站正好当作一个写日记的平台，记录写可以分享的东西还算是不错的hhhhhh。");
document.writeln("                                                                             ——————2020.03.27留-->");
document.writeln("<head>");
document.writeln("  <meta charset=\'utf-8\'>");
document.writeln("  <meta name=\'viewport\' content=\'width=device-width, initial-scale=1, shrink-to-fit=no\'>");
document.writeln("  <meta http-equiv=\'x-ua-compatible\' content=\'ie=edge\'>");
document.writeln("  <title>China PSC</title>");
document.writeln("  <!-- ico图标啦~~~-->");
document.writeln("");
document.writeln("  <link rel=\'icon\' href=\'img/ico图标.ico\' type=\'image/x-icon\'>");
document.writeln("  <link rel=\'shortcut icon\' href=\'img/ico图标.ico\' type=\'image/x-icon\'>");
document.writeln("");
document.writeln("  <!-- Font Awesome -->");
document.writeln("  <link rel=\'stylesheet\' href=\'css/all.css\'>");
document.writeln("  <!-- Bootstrap core CSS -->");
document.writeln("  <link href=\'css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("  <!-- Material Design Bootstrap -->");
document.writeln("  <link href=\'css/mdb.min.css\' rel=\'stylesheet\'>");
document.writeln("  <!-- Your custom styles (optional) -->");
document.writeln("  <link href=\'css/style.min.css\' rel=\'stylesheet\'>");
document.writeln("  <style type=\'text/css\'>");
document.writeln("    /* Necessary for full page carousel*/");
document.writeln("    html,");
document.writeln("    body,");
document.writeln("");
document.writeln("    header,");
document.writeln("    .view {");
document.writeln("      height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* Carousel*/");
document.writeln("    .carousel,");
document.writeln("    .carousel-item,");
document.writeln("    .carousel-item.active {");
document.writeln("      height: 100%;");
document.writeln("    }");
document.writeln("    .carousel-inner {");
document.writeln("      height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    @media (min-width: 800px) and (max-width: 850px) {");
document.writeln("      .navbar:not(.top-nav-collapse) {");
document.writeln("          background: #1C2331!important;");
document.writeln("      }");
document.writeln("  }");
document.writeln("");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("  <!-- Navbar -->");
document.writeln("  <nav class=\'navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar\'>");
document.writeln(" ");
document.writeln("    <div class=\'container\'>");
document.writeln("");
document.writeln("      <!-- Brand -->");
document.writeln("");
document.writeln("      <a class=\'navbar-brand\' href=\'https://china-psc.com/\'>");
document.writeln("        <img src=\'img/图标.png\' style=\'width:250px\'>");
document.writeln("      </a>");
document.writeln("");
document.writeln("      <!-- Collapse -->");
document.writeln("      <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\' aria-controls=\'navbarSupportedContent\'");
document.writeln("        aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("        <span class=\'navbar-toggler-icon\'></span>");
document.writeln("      </button>");
document.writeln("");
document.writeln("      <!-- Links -->");
document.writeln("      <div class=\'collapse navbar-collapse\' id=\'navbarSupportedContent\'>");
document.writeln("");
document.writeln("        <!-- Left -->");
document.writeln("        <ul class=\'navbar-nav mr-auto\'>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link\' href=\'index.html\'>主页");
document.writeln("              <span class=\'sr-only\'>(current)</span>");
document.writeln("            </a>");
document.writeln("          </li>          ");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link\' href=\'briefing.html\'>实验室简介</a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item dropdown\'>");
document.writeln("            <a class=\'nav-link\' id=\'navbarDropdownMenuLink\' data-toggle=\'dropdown\' aria-haspopup=\'true\'");
document.writeln("            aria-expanded=\'false\'>成员</a>");
document.writeln("            <div class=\'dropdown-menu dropdown-primary rgba-black-strong scrolling-navbar\' aria-labelledby=\'navbarDropdownMenuLink\'>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'member.html\'>学术领头人</a>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'member.html#mao\'>学术顾问</a>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'member.html#mao2\'>研究生</a>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'member.html#mao3\'>毕业生</a>");
document.writeln("            </div>");
document.writeln("          </li>     ");
document.writeln("          <li class=\'nav-item dropdown\'>");
document.writeln("            <a class=\'nav-link\' id=\'navbarDropdownMenuLink\' data-toggle=\'dropdown\' aria-haspopup=\'true\'");
document.writeln("            aria-expanded=\'false\'>科学研究</a>");
document.writeln("            <div class=\'dropdown-menu dropdown-primary rgba-black-strong scrolling-navbar\' aria-labelledby=\'navbarDropdownMenuLink\'>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'direction.html\'>研究方向</a>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'essay.html\'>学术成果</a>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'facility.html\'>仪器设备</a>");
document.writeln("            </div>");
document.writeln("          </li>              ");
document.writeln("          <li class=\'nav-item dropdown\'>");
document.writeln("            <a class=\'nav-link\' id=\'navbarDropdownMenuLink\' data-toggle=\'dropdown\' aria-haspopup=\'true\'");
document.writeln("            aria-expanded=\'false\'>学术活动</a>");
document.writeln("            <div class=\'dropdown-menu dropdown-primary rgba-black-strong scrolling-navbar\' aria-labelledby=\'navbarDropdownMenuLink\' style=\'min-width:200px\'>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'articlelist2.html\'>学术会议</a>");
document.writeln("              <a class=\'nav-link muted-text\' href=\'bigchuang.html\'style=\'font-size:15px;\'>大学生创新创业训练项目</a>");
document.writeln("            </div>");
document.writeln("          </li>         ");
document.writeln("                    ");
document.writeln("           <li class=\'nav-item\'>");
document.writeln("             	<a class=\'nav-link\' href=\'articlelist1.html\'>合作交流</a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("          	<a class=\'nav-link\' href=\'resources.html\'>资源分享</a>");
document.writeln("          </li>");
document.writeln("           <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link\' href=\'construction.html\'>团队建设</a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link\' href=\'contactus.html\'>联系我们</a>");
document.writeln("          </li>");
document.writeln("");
document.writeln("        </ul>");
document.writeln("");
document.writeln("      ");
document.writeln("");
document.writeln("        <!-- Right -->");
document.writeln("        <!--<ul class=\'navbar-nav nav-flex-icons\'>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a href=\'https://www.facebook.com/mdbootstrap\' class=\'nav-link\' target=\'_blank\'>");
document.writeln("              <i class=\'fab fa-facebook-f\'></i>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a href=\'https://twitter.com/MDBootstrap\' class=\'nav-link\' target=\'_blank\'>");
document.writeln("              <i class=\'fab fa-twitter\'></i>");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("          <li class=\'nav-item\'>");
document.writeln("            <a href=\'https://github.com/mdbootstrap/bootstrap-material-design\' class=\'nav-link border border-light rounded waves-effect waves-light\'");
document.writeln("              target=\'_blank\'>");
document.writeln("              <i class=\'fab fa-github mr-2\'></i>MDB GitHub");
document.writeln("            </a>");
document.writeln("          </li>");
document.writeln("        </ul>-->");
document.writeln("");
document.writeln("      </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("  </nav>");
document.writeln("  <!-- Navbar -->");
document.writeln("");
document.writeln("<!-- SCRIPTS -->");
document.writeln("  <!-- JQuery -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/jquery-3.4.1.min.js\'></script>");
document.writeln("  <!-- Bootstrap tooltips -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/popper.min.js\'></script>");
document.writeln("  <!-- Bootstrap core JavaScript -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/bootstrap.min.js\'></script>");
document.writeln("  <!-- MDB core JavaScript -->");
document.writeln("  <script type=\'text/javascript\' src=\'js/mdb.min.js\'></script>");
document.writeln("  <!-- Initializations -->");
document.writeln("  <script type=\'text/javascript\'>");
document.writeln("    // Animations initialization");
document.writeln("    new WOW().init();");
document.writeln("  </script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");
document.writeln("");